name = "spotify-playlists"
compatibility_flags = ["nodejs_compat"]

[vars]
SPOTIFY_CLIENT_ID = "73b8fc71d93f4977acb3103bbd69a1b5"
SPOTIFY_CLIENT_SECRET = "dad43a6e04054abd8905e0cc5683187a"
REDIRECT_URI = "http://localhost:8788/callback"
